/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      extend: {
        colors: {
          light: {
            background: "#FFFFFF",
            "background-secondary": "#F0FDF4",
            "background-muted": "#D1FAE5",
            foreground: "#14532D",
            "foreground-secondary": "#374151",
            "foreground-muted": "#6B7280",
            card: "#FFFFFF",
            "card-foreground": "#14532D",
            border: "#D1D5DB",
            input: "#F3F4F6",
            ring: "#059669",
            primary: "#059669",
            "primary-foreground": "#FFFFFF",
            secondary: "#F3F4F6",
            "secondary-foreground": "#14532D",
            success: "#10B981",
            warning: "#F59E0B",
            error: "#DC2626",
            info: "#059669",
          },
          dark: {
            background: "#111827",
            "background-secondary": "#1F2937",
            "background-muted": "#064E3B",
            foreground: "#F9FAFB",
            "foreground-secondary": "#E5E7EB",
            "foreground-muted": "#9CA3AF",
            card: "#1F2937",
            "card-foreground": "#F9FAFB",
            border: "#374151",
            input: "#4B5563",
            ring: "#34D399",
            primary: "#34D399",
            "primary-foreground": "#111827",
            secondary: "#4B5563",
            "secondary-foreground": "#F9FAFB",
            success: "#22C55E",
            warning: "#EAB308",
            error: "#EF4444",
            info: "#34D399",
          },
        },
      },
    },
  },
  plugins: [],
};
